### ISSUE TITLE
你好，关于这本书，能否放到我们的平台。

### ISSUE THREAD

**Issue by wenquan0hf** [ahangchen/How-to-Be-A-Programmer-CN#4]
我们是wiki.jikexueyuan.com
我们帮助提供一些翻译者，做在线协作，这个前提是根据兴趣的。
然后我们平台是免费开源的，展示效果很好，还可以实时更新，做连载。
最重要的是，这本书很好，而且您的翻译我看着很舒服。
不知道您有没有兴趣，我们没有任何强制性要求，而且会严格遵守Licensed under Creative Commons Attribution-ShareAlike 4.0 International License.。

**Comment by ahangchen** [comment]
在引言标记一下英文版的github地址:
https://github.com/braydie/HowToBeAProgrammer
和中文版github地址：
https://github.com/ahangchen/How-to-Be-A-Programmer-CN
即可。
另外现在只是翻译了一部分，其实一开始我是想一个人翻译完然后再校正的。
如果您有其他的翻译者协助我，可以在github上给我提PR；
可以对已翻译部分提修改建议，或者翻译剩下的部分（为了避免重复工作可以从 3-Advanced部分开始动手）；
翻译有个要求是尽量不丢作者的词汇。

**Comment by wenquan0hf** [comment]
nice。好的。我尽快推送一个PR 做一点配置。

**Comment by ahangchen** [comment]
@wenquan0hf 我昨天在reps的README.MD加上了工程的地址，如果你们需要根据自己的网站做一些配置的话，可以fork修改，不一定要merge回来。

**Comment by wenquan0hf** [comment]
@ahangchen  我看到您已经翻译完成，我会做一定配置，然后上线我们的平台。

**Comment by ahangchen** [comment]
@wenquan0hf  好的

**Comment by wenquan0hf** [comment]
@ahangchen  您看下，这里是我们整理的Wiki 版。右上角点击作者名字会回到你的主页。http://wiki.jikexueyuan.com/project/how-to-be-a-programmer/
可以生成电子书吗？

**Comment by ahangchen** [comment]
@wenquan0hf 可以
